name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'frontend/**'  

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Build Frontend
        run: |
          cd frontend
          npm run build  
          if [ ! -d "dist" ]; then echo "Build failed: dist directory does not exist."; exit 1; fi
      - name: Copy routes.json
        run: |
          cd frontend
          cp routes.json dist/  # Ensure routes.json is copied to the output directory
      - name: Check if routes.json is present
        run: |
          cd frontend
          ls dist/  # List files in dist to check if routes.json is there
      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_DESERT_04EA24410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "./frontend" # App source code path
          api_location: "./api" # Api source code path - optional
          output_location: "dist"
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_DESERT_04EA24410 }}
          action: "close"
